#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SWITCHES_ROW 3
#define SENSORS_ROW 8
#define INPUT_ROW 10
#define LAST_FUNCTON_ROW 11
#define FUNCTION_RESULT_ROW 12

#define NUM_TASKS {20,2,1}
#define MAX_NUM_TASKS 23
#define NAME_SERVER_TID 20
#define IDLE_TID 1

#define TASK_SIZES {20480,81920,614400}
#define USER_STACK_SIZE 2048
#define SENDER_QUEUE_SIZE 5

#define INACTIVE 0
#define READY 1
#define SEND_WAIT 2
#define RECEIVE_WAIT 3
#define REPLY_WAIT 4

#define MAX_NUM_TRIGGERED_SENSORS 2
#define MAX_NUM_TRAINS 2

#endif
