#ifndef TASKS_H
#define TASKS_H

#include <stdint.h>

extern uint64_t* p_idle_task_total;
extern uint64_t* p_program_start;

typedef enum {
  CLOCK_NOTIFIER_PRIORITY,
  CLOCK_PRIORITY,

  NAME_SERVER_PRIORITY,
  
  MOUT_TX_NOTIFIER_PRIORITY,
  MOUT_CTS_NOTIFIER_PRIORITY,
  MIN_NOTIFIER_PRIORITY,
  MIO_PRIORITY,

  TRAIN_SERVER_PRIORITY,
  SENSOR_UPDATE_PRIORITY,
  SWITCHES_PRIORITY,
  
  CIN_NOTIFIER_PRIORITY,
  CIN_PRIORITY,

  COUT_NOTIFIER_PRIORITY,
  COUT_PRIORITY,

  PATH_FINDING_PRIORITY,
  USER_INPUT_PRIORITY,
  REVERSE_PRIORITY,
  DELAY_STOP_PRIORITY,
  CONSOLE_TIME_PRIORITY,

  PRIORITY_NONE
} priorities;

void idle_task();
void time_user();
void rootTask();
void oldRootTask();

#endif